export const JOURNEYS = [
  {
    id: 'asana',
    label: 'Movement & Asana',
    icon: '🧘',
    categoryKey: 'asana',
    description: 'Master poses, transitions and movement mechanics',
    levels: [
      { id: 'foundations', label: 'Pose Foundations', description: 'Learn the basics of key yoga poses' },
      { id: 'mechanics', label: 'Pose Mechanics', description: 'Understand alignment and body mechanics' },
      { id: 'transitions', label: 'Transitions', description: 'Flow between poses with intention' },
      { id: 'variations', label: 'Advanced Variations', description: 'Explore deeper expressions' },
      { id: 'teaching', label: 'Teaching the Pose', description: 'Communicate poses to students' },
    ],
    focuses: [
      { id: 'standing', label: 'Standing Poses', icon: '🏔️' },
      { id: 'seated', label: 'Seated Poses', icon: '🪷' },
      { id: 'backbends', label: 'Backbends', icon: '🌉' },
      { id: 'balance', label: 'Balances', icon: '⚖️' },
      { id: 'sun_sal', label: 'Sun Salutations', icon: '☀️' },
    ],
  },
  {
    id: 'anatomy',
    label: 'Anatomy',
    icon: '🦴',
    categoryKey: 'anatomy',
    description: 'Understand the body behind the practice',
    levels: [
      { id: 'muscles', label: 'Major Muscle Groups', description: 'Key muscles in yoga movement' },
      { id: 'joints', label: 'Joint Mechanics', description: 'How joints move and are protected' },
      { id: 'injury', label: 'Injury Prevention', description: 'Safe practice principles' },
      { id: 'application', label: 'Application to Poses', description: 'Anatomy in action' },
    ],
    focuses: [
      { id: 'hips', label: 'Hips & Pelvis', icon: '🦿' },
      { id: 'spine', label: 'Spine & Core', icon: '🫀' },
      { id: 'shoulders', label: 'Shoulders & Arms', icon: '💪' },
      { id: 'legs', label: 'Legs & Feet', icon: '🦵' },
    ],
  },
  {
    id: 'cueing',
    label: 'Teaching & Cueing',
    icon: '🗣️',
    categoryKey: 'cueing',
    description: 'Guide students with clarity and presence',
    levels: [
      { id: 'basics', label: 'Basic Cues', description: 'Simple, clear instructions' },
      { id: 'alignment', label: 'Alignment Cues', description: 'Precise body positioning language' },
      { id: 'imagery', label: 'Verbal Imagery', description: 'Evocative and inspiring language' },
      { id: 'presence', label: 'Teaching Presence', description: 'Holding space and energy' },
    ],
    focuses: [
      { id: 'action', label: 'Action Cues', icon: '⚡' },
      { id: 'breath', label: 'Breath Cues', icon: '🌬️' },
      { id: 'imagery', label: 'Imagery Cues', icon: '🎨' },
      { id: 'adjustment', label: 'Adjustments', icon: '🤝' },
    ],
  },
  {
    id: 'breathwork',
    label: 'Breathwork',
    icon: '🌬️',
    categoryKey: 'breathwork',
    description: 'Develop pranayama and breath-movement connection',
    levels: [
      { id: 'awareness', label: 'Breath Awareness', description: 'Observing and deepening breath' },
      { id: 'pranayama', label: 'Pranayama Techniques', description: 'Classical breathing practices' },
      { id: 'integration', label: 'Breath + Movement', description: 'Linking breath and asana' },
      { id: 'teaching', label: 'Teaching Breathwork', description: 'Guiding others in breath practices' },
    ],
    focuses: [
      { id: 'ujjayi', label: 'Ujjayi Breath', icon: '🌊' },
      { id: 'kapalabhati', label: 'Kapalabhati', icon: '🔥' },
      { id: 'nadi', label: 'Nadi Shodhana', icon: '☯️' },
      { id: 'retention', label: 'Breath Retention', icon: '⏸️' },
    ],
  },
  {
    id: 'philosophy',
    label: 'Philosophy',
    icon: '📿',
    categoryKey: 'philosophy',
    description: 'Connect to the wisdom traditions of yoga',
    levels: [
      { id: 'foundations', label: 'Foundations', description: 'Core concepts and history' },
      { id: 'sutras', label: 'Yoga Sutras', description: 'Patanjali\'s essential teachings' },
      { id: 'themes', label: 'Themes for Classes', description: 'Weaving philosophy into teaching' },
      { id: 'integration', label: 'Integration in Teaching', description: 'Living and sharing the philosophy' },
    ],
    focuses: [
      { id: 'yamas', label: 'Yamas & Niyamas', icon: '📖' },
      { id: 'chakras', label: 'Chakras', icon: '⭕' },
      { id: 'sutras', label: 'Yoga Sutras', icon: '📜' },
      { id: 'history', label: 'History of Yoga', icon: '🏛️' },
    ],
  },
  {
    id: 'programming',
    label: 'Class Design',
    icon: '📋',
    categoryKey: 'programming',
    description: 'Architect intelligent, meaningful sequences',
    levels: [
      { id: 'basics', label: 'Basic Sequencing', description: 'Structure and flow principles' },
      { id: 'peak', label: 'Peak Pose Classes', description: 'Building toward a highlight pose' },
      { id: 'themed', label: 'Theme-Based Classes', description: 'Cohesive philosophical themes' },
      { id: 'advanced', label: 'Advanced Architecture', description: 'Complex, layered programming' },
    ],
    focuses: [
      { id: 'warmup', label: 'Warm-Up Design', icon: '🔥' },
      { id: 'peak', label: 'Peak Pose Building', icon: '🏔️' },
      { id: 'cooldown', label: 'Cool-Down', icon: '❄️' },
      { id: 'timing', label: 'Timing & Pacing', icon: '⏱️' },
    ],
  },
];

export const getJourney = (id) => JOURNEYS.find(j => j.id === id);