import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

export default async function handler(req: Request): Promise<Response> {
  const base44 = createClientFromRequest(req);
  const body = await req.json();

  const {
    lesson_id,
    script_text,
    avatar_id,
    voice_id,
    title = 'YogaPath Lesson',
    background_url,
  } = body;

  const apiKey = Deno.env.get('SYNTHESIA_API_KEY');
  if (!apiKey) {
    return Response.json({ error: 'SYNTHESIA_API_KEY environment variable not set' }, { status: 500 });
  }

  if (!script_text || !avatar_id) {
    return Response.json({ error: 'script_text and avatar_id are required' }, { status: 400 });
  }

  const input: Record<string, unknown> = {
    avatarSettings: {
      avatarId: avatar_id,
      horizontalAlign: 'center',
      scale: 1,
      style: 'rectangular',
    },
    scriptText: script_text,
  };

  // Only include voice if provided — Synthesia uses avatar's default voice otherwise
  if (voice_id) {
    input.avatarSettings = { ...input.avatarSettings as object, voice: voice_id };
  }

  if (background_url) {
    input.background = background_url;
  }

  const payload = {
    test: false,
    title,
    description: `Generated by YogaPath for lesson ${lesson_id || 'unknown'}`,
    visibility: 'private',
    input: [input],
  };

  let synthResp: Response;
  try {
    synthResp = await fetch('https://api.synthesia.io/v2/videos', {
      method: 'POST',
      headers: {
        'Authorization': apiKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    });
  } catch (e) {
    return Response.json({ error: `Network error reaching Synthesia: ${e.message}` }, { status: 502 });
  }

  const data = await synthResp.json();

  if (!synthResp.ok) {
    return Response.json({
      error: data?.message || data?.error || data?.detail || JSON.stringify(data),
      synthesia_data: data,
    }, { status: synthResp.status });
  }

  const video_id = data?.id;

  if (lesson_id && video_id) {
    try {
      await base44.asServiceRole.entities.CurriculumLesson.update(lesson_id, {
        synthesia_video_id: video_id,
        synthesia_status: 'processing',
      });
    } catch (_) {}
  }

  return Response.json({ video_id, status: 'processing', raw: data });
}
